load("//tools:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

toolchain_type(name = "toolchain_type")

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    deps = [
        "//fable/private:providers",
        "//fable/private:rules",
    ],
)

bzl_library(
    name = "extensions",
    srcs = ["extensions.bzl"],
    deps = [
        ":nuget",
        ":repositories",
        ":versions",
    ],
)

bzl_library(
    name = "nuget",
    srcs = ["nuget.bzl"],
    doc_deps = ["@rules_dotnet//dotnet:defs"],
    deps = [":versions"],
)

bzl_library(
    name = "repositories",
    srcs = ["repositories.bzl"],
    deps = [":versions"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
)
