load("//tools:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "rules",
    srcs = ["rules.bzl"],
    doc_deps = ["@rules_dotnet//dotnet:defs"],
    deps = [":providers"],
)

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)
