bazel_dep(name = "rules_fable", version = "0.0.0")
bazel_dep(name = "rules_nodejs", version = "6.7.4")
bazel_dep(name = "aspect_rules_js", version = "3.2.1")

local_path_override(
    module_name = "rules_fable",
    path = "../..",
)

fable_toolchains = use_extension("@rules_fable//fable:extensions.bzl", "toolchains")
fable_toolchains.toolchain(fable_version = "4.29.0")
use_repo(fable_toolchains, "fable_toolchains")
register_toolchains("@fable_toolchains//:fable_toolchain")
