bazel_dep(name = "rules_fable", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.8.2", dev_dependency = True)

bazel_dep(name = "rules_dotnet", version = "0.21.5")

local_path_override(
    module_name = "rules_fable",
    path = "../..",
)

fable_toolchains = use_extension("@rules_fable//fable:extensions.bzl", "toolchains")
fable_toolchains.toolchain(fable_version = "4.29.0")
use_repo(fable_toolchains, "fable_toolchains")

register_toolchains("@fable_toolchains//:fable_toolchain")
